# -*- coding: utf-8 -*-
"""Text Gen with GPT Neo 1.5B Models on Hugging Face Transformers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UByjdT5l_VSsCBqtQvVygDexJYQ0pUma
"""

!pip install git+https://github.com/huggingface/transformers.git

from transformers import pipeline

generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B')



text = generator("import pandas as pd \n import numpy as np\n " , do_sample=True, min_length=50, num_return_sequences=5)

text

print(text[0]['generated_text'])

